// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, Bucket, KvCache, Logger, MRNObject, ServiceStub, SqlDatabase, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  INPUT_BUCKET: Bucket;
  logger: Logger;
  mem: KvCache;
  OUTPUT_BUCKET: Bucket;
  tracer: Tracer;
  TRACKING_DB: SqlDatabase;
  UPLOAD_API: ServiceStub<import('../upload-api/index.js').default>;
}
