// AI Expert System Prompts for Virtual C-Suite

import { CFO_AGENT_PROMPT } from '../prompts/cfo_agent.js';
import { CMO_AGENT_PROMPT } from '../prompts/cmo_agent.js';
import { COO_AGENT_PROMPT } from '../prompts/coo_agent.js';
import { CEO_AGENT_PROMPT } from '../prompts/ceo_agent.js';

// --- METHODS ---

export function getCFOPrompt(businessData: string): string {
  return `BUSINESS DATA:
${businessData}

${CFO_AGENT_PROMPT}`;
}

export function getCMOPrompt(businessData: string): string {
  return `BUSINESS DATA:
${businessData}

${CMO_AGENT_PROMPT}`;
}

export function getCOOPrompt(businessData: string): string {
  return `BUSINESS DATA:
${businessData}

${COO_AGENT_PROMPT}`;
}

export function getCEOSynthesisPrompt(
  cfoAnalysis: string,
  cmoAnalysis: string,
  cooAnalysis: string
): string {
  // Replace the placeholders in the markdown with the actual reports
  return CEO_AGENT_PROMPT
    .replace('[Insert Output from CFO Agent]', cfoAnalysis)
    .replace('[Insert Output from CMO Agent]', cmoAnalysis)
    .replace('[Insert Output from COO Agent]', cooAnalysis)
    .replace('[Insert Context from Business Owner]', '(Refer to Business Data provided in previous steps)');
}

export function formatFinalReport(
  requestId: string,
  cfoAnalysis: string,
  cmoAnalysis: string,
  cooAnalysis: string,
  ceoSynthesis: string
): string {
  const timestamp = new Date().toISOString();

  return `# Virtual C-Suite Strategic Analysis

**Request ID:** ${requestId}
**Generated:** ${timestamp}

---

## 💼 CFO Analysis: Financial Health & Risk Management

${cfoAnalysis}

---

## 📈 CMO Analysis: Growth & Market Strategy

${cmoAnalysis}

---

## ⚙️ COO Analysis: Operations & Efficiency

${cooAnalysis}

---

## 🎯 CEO Strategic Synthesis & Recommendations

${ceoSynthesis}

---

## 📋 Next Steps

Review the priority actions above and begin implementation with the highest-priority items. This analysis was generated by Virtual C-Suite, providing Fortune 500-level strategic intelligence to help you make better business decisions.

---

*Generated with Virtual C-Suite - Democratizing Strategic Intelligence for SMEs*
`;
}

// CEO Chat Board Consultation Prompts

export function getBoardConsultationDecisionPrompt(userMessage: string): string {
  return `You are a strategic decision-making system. Analyze the following user message to determine which C-suite executives should be consulted for expert input.

USER MESSAGE:
"${userMessage}"

DECISION CRITERIA:
- CFO (Chief Financial Officer): Budget, profitability, cash flow, financial risk, pricing, revenue, costs, margins, financial projections, investments, fundraising
- CMO (Chief Marketing Officer): Branding, customer acquisition, market growth, advertising, marketing strategy, customer segments, brand positioning, market trends, customer retention
- COO (Chief Operating Officer): Logistics, efficiency, personnel, process management, operations, supply chain, team structure, hiring, scalability, execution

RULES:
1. If the question is about general leadership, strategy, vision, or casual conversation, consult NO ONE (return empty array)
2. If the question clearly relates to ONE domain, return only that executive
3. If the question spans MULTIPLE domains, return all relevant executives
4. Be selective - only consult when domain expertise would genuinely add value

Respond ONLY with valid JSON in this exact format:
{
  "executives": ["CFO", "CMO", "COO"],
  "reasoning": "Brief explanation of why these executives were selected"
}

Or for no consultation:
{
  "executives": [],
  "reasoning": "Brief explanation"
}

IMPORTANT: Output ONLY the JSON object, no additional text.`;
}

export function getCFOChatPrompt(conversationHistory: string, userQuestion: string): string {
  return `CONVERSATION HISTORY:
${conversationHistory}

CURRENT QUESTION:
"${userQuestion}"

${CFO_AGENT_PROMPT}`;
}

export function getCMOChatPrompt(conversationHistory: string, userQuestion: string): string {
  return `CONVERSATION HISTORY:
${conversationHistory}

CURRENT QUESTION:
"${userQuestion}"

${CMO_AGENT_PROMPT}`;
}

export function getCOOChatPrompt(conversationHistory: string, userQuestion: string): string {
  return `CONVERSATION HISTORY:
${conversationHistory}

CURRENT QUESTION:
"${userQuestion}"

${COO_AGENT_PROMPT}`;
}

export function getCEOChatSynthesisPrompt(
  conversationHistory: string,
  userQuestion: string,
  boardAdvice: { role: string; advice: string }[],
  brandContext?: string | null
): string {
  const adviceSection = boardAdvice.length > 0
    ? boardAdvice.map(({ role, advice }) => `${role} INPUT:\n${advice}`).join('\n\n')
    : 'No board consultation was needed for this query.';

  const brandSection = brandContext
    ? `\n\nBRAND CONTEXT (User's Brand Guidelines):\n${brandContext}\n\nIMPORTANT: All recommendations must align with these brand guidelines and company values.`
    : '';

  // For Chat Synthesis, we map the Board Advice to the Placeholders if possible, or append it explicitly.
  // Since the mapping isn't 1:1 (Chat boardAdvice is dynamic), we will inject the advice explicitly 
  // and do a best-effort replacement of placeholders to avoid confusion.

  let prompt = CEO_AGENT_PROMPT;

  // Attempt to fill placeholders if likely matches found in adviceSection (this is tricky with dynamic specific advice)
  // Instead, we will replace the 'INPUT CONTEXT' block entire in the generated prompt string if we could, 
  // but simpler is to just prepend the Chat Context and let the Model reconcile the "Input Context" section at the end.

  // Better approach for Chat: Replace the [Insert Output...] lines with "See BOARD CONSULTATION RESULTS above".
  prompt = prompt
    .replace('[Insert Context from Business Owner]', brandSection || '(See Conversation History)')
    .replace('[Insert Output from CFO Agent]', '(See CFO INPUT in Board Consultation Results if present)')
    .replace('[Insert Output from CMO Agent]', '(See CMO INPUT in Board Consultation Results if present)')
    .replace('[Insert Output from COO Agent]', '(See COO INPUT in Board Consultation Results if present)');

  return `CONVERSATION HISTORY:
${conversationHistory}

CURRENT USER QUESTION:
"${userQuestion}"

BOARD CONSULTATION RESULTS:
${adviceSection}

${prompt}`;
}
